[package]
name = "i3helper"
version = "0.1.0"
authors = ["Vlad Vasiliu <vladvasiliun@yahoo.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fern = "0.6.0"
futures = "0.3.5"
log = "0.4.11"
tokio = { version = "0.2.22", features = ["rt-core", "sync"] }
tokio-i3ipc = "0.10.0"
tokio-util = "0.3.1"
