[package]
name = "i3helper"
version = "0.1.0"
authors = ["Vlad Vasiliu <vladvasiliun@yahoo.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fern = "0.6.0"
futures = "0.3.15"
log = "0.4.14"
tokio = { version = "1.6", features = ["macros", "rt-multi-thread", "signal", "sync"] }
tokio-i3ipc = "0.12"
tokio-stream = "0.1.6"
tokio-util = "0.6.5"
